import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

def main():
    lambda_val = 2.0
    t_max = 4.0
    
    plt.figure(figsize=(10, 6))

    # We loop through the 5 independent "universes" generated by our code

    files_found = 0
    for i in range(5):
        filename = f"../data/pop_run_{i}.csv"
        
        if os.path.exists(filename):
            df = pd.read_csv(filename)
            files_found += 1
            
            plt.step(df['time'], df['population'], where='post', 
                     color='blue', alpha=0.4, linewidth=1.5,
                     label="C++ Simulations" if i == 0 else "")
        else:
            print(f"[Info] File {filename} not found (others might be present).")

    if files_found == 0:
        print("ERROR : No population data found. Please run the C++ engine first.")
        return

    # Comparison with the theoretical average: E[N_t] = N_0 * exp(lambda * t)

    t_theo = np.linspace(0, t_max, 200)
    y_theo = np.exp(lambda_val * t_theo) 
    
    plt.plot(t_theo, y_theo, 'k--', linewidth=2, label=r"Theoretical Mean ($e^{\lambda t}$)")

    # On a Log scale, an exponential function becomes a straight line
    # This visual proof is much stronger than a simple curve

    plt.yscale('log')
    
    plt.title(r"Demographic Explosion (Yule Process)", fontsize=14)
    plt.xlabel("Time ($t$)", fontsize=12)
    plt.ylabel(r"Population Size (Log Scale)", fontsize=12)
    plt.legend(fontsize=11)
    
    plt.grid(True, which="both", alpha=0.3) 
    
    out_file = "../data/graph_yule_explosion.png"
    plt.savefig(out_file, dpi=150)
    print(f"[OK] Graph saved: {out_file}")
    plt.show()

if __name__ == "__main__":
    main()