import pandas as pd
import matplotlib.pyplot as plt
import os

def main():

    # Paths to files generated by C++
    file_small = "../data/traj_small.csv"
    file_large = "../data/traj_large.csv"

    # Safety check
    if not os.path.exists(file_small) or not os.path.exists(file_large):
        print(f"ERROR: Files not found ({file_small} or {file_large}).")
        print("Did you run './cell_sim.exe' in the build folder?")
        return

    # Loading data
    df_small = pd.read_csv(file_small)
    df_large = pd.read_csv(file_large)

    # Plot configuration
    plt.figure(figsize=(10, 6))
    
    # Trajectory 1 : Small mass starting value
    plt.plot(df_small['time'], df_small['mass'], 
             label=r'$x_0=0.1$', color='blue', alpha=0.8, linewidth=1.5)
    
    # Trajectory 2 : Huge mass starting value
    plt.plot(df_large['time'], df_large['mass'], 
             label=r'$x_0=10.0$', color='red', alpha=0.8, linewidth=1.5)

    # Layout 
    plt.title(r"Memory Loss : Convergence of Mass Trajectories $X_t$", fontsize=14)
    plt.xlabel("Time ($t$)", fontsize=12)
    plt.ylabel("Cell Mass ($X_t$)", fontsize=12)
    plt.legend(fontsize=11)
    plt.grid(True, alpha=0.3)
    
    # Save
    out_file = "../data/graph_mass_memory_loss.png"
    plt.savefig(out_file, dpi=150)
    print(f"[OK] Plot saved: {out_file}")
    plt.show()

if __name__ == "__main__":
    main()